### ISSUE TITLE
SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by snd666** [boochow/prologue_tools#1]
Hello,

excuse me please for this request. I don't know if it is an issue or maybe my mistake. Just installed Python 3.10.7 and tried to convert some Prologue patches to Minilogue. Got this error:
"File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\prlg2mnlgxd.py", line 69
    <title>prologue_tools/prlg2mnlgxd.py at main · boochow/prologue_tools · GitHub</title>
                                                 ^
SyntaxError: invalid character '·' (U+00B7)

Can you help me?
Thanks a lot.

Kind regards
Peter

**Comment by boochow** [comment]
Hi, 
I tested this script on my new PC using Python3.10.7 installed from Microsoft Store. (I usually use Linux)
The script is copied from the GitHub repo (click the "copy raw content" icon, paste it to memopad, and save it to a file).
I got no error you mentioned, but I found that the input file (prologue program file) must be specified as a full path name, like:
```
$file = Convert-Path .\001_Runner_Brass.prlgprog
python.exe .\prlg2mnlg.py $file
```

**Comment by snd666** [comment]
Hi,

thank you very much!
The "copy raw content" & "save to file" method worked perfekt.
I'm using only Windows 10/11.
Here open CMD in the "python" directory and as you mentioned the full path to the "prlgprog":

python.exe prlg2mnlgxdPP.py "E:\_Sound Tools\A_Synthesizer\0.0. kORG-Minilogue XD\Converter_Prol_XD\2PoleGEO.prlgprog"

I've converted 200 patches. I've bought them for 45$ and didn't see that they are only for the Prologue...
Have a nice day!

Kind regards
Peter Praiss

**Comment by boochow** [comment]
Peter, thank you for testing.
I fixed the code, so you don't need to give a full path name now.
