### ISSUE TITLE
Need help running the script

### ISSUE THREAD

**Issue by PhntmPenguin12** [boochow/prologue_tools#2]
Hi, I'm not sure whether I am running this script correctly or not. I ran the 'prlg2mnlgxd' script with Python in the same directory as the prologue patch I want to convert. The command prompt flashes on the screen and closes immediately, but no files have been converted. Am I doing this right?

**Comment by boochow** [comment]
Hi, are you using Windows OS? If so, the easiest way to use prlog2mnlgxd is to use the windows executable version, not the script plus python.
Please watch this video for details.

[How to convert patches between minilogue xd and prologue
](https://www.youtube.com/watch?v=zGdHntEldRU
)

**Comment by PhntmPenguin12** [comment]
I followed the video and it worked! Thank you so much!
